### ISSUE TITLE
Reflection Error running under Cauldron 1.7.10

### ISSUE THREAD

**Issue by gixmy** [bergerkiller/BKCommonLib#26]
I have loaded up the latest versions of Cauldron (previously mcpc) and BKCommonLib, Train Carts. On startup I get the following crash. No other plugins / mods were loaded when this happened:

[08:50:39 INFO]: [BKCommonLib] Loading BKCommonLib v1.59-SNAPSHOT
[08:50:40 ERROR]: [BKCommonLib] [Reflection] Method 'burn(float)' does not exist in class file net.minecraft.entity.Entity (Update BKCommonLib?)
[08:50:40 ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.internal.CommonPlugin.handleReflectionMissing(CommonPlugin.java:104)
[08:50:40 ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.reflection.SafeMethod.load(SafeMethod.java:87)
[08:50:40 ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.reflection.SafeMethod.<init>(SafeMethod.java:54)
[08:50:40 ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.reflection.ClassTemplate.getMethod(ClassTemplate.java:253)
[08:50:40 ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.reflection.classes.EntityRef.<clinit>(EntityRef.java:53)
[08:50:40 ERROR]: [BKCommonLib] at java.lang.Class.forName0(Native Method)
[08:50:40 ERROR]: [BKCommonLib] at java.lang.Class.forName(Unknown Source)
[08:50:40 ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.Common.loadClasses(Common.java:111)
[08:50:40 ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.internal.CommonClasses.loadCommon(CommonClasses.java:59)
[08:50:40 ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.internal.CommonClasses.loadRef(CommonClasses.java:45)
[08:50:40 ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.internal.CommonClasses.init(CommonClasses.java:19)
[08:50:40 ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.internal.CommonPlugin.onLoad(CommonPlugin.java:315)
[08:50:40 ERROR]: [BKCommonLib] at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:325)
[08:50:40 ERROR]: [BKCommonLib] at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:458)
[08:50:40 ERROR]: [BKCommonLib] at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:136)
[08:50:40 ERROR]: [BKCommonLib] at net.minecraft.world.World.<init>(World.java:350)
[08:50:40 ERROR]: [BKCommonLib] at net.minecraft.world.WorldServer.<init>(WorldServer.java:153)
[08:50:40 ERROR]: [BKCommonLib] at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:356)
[08:50:40 ERROR]: [BKCommonLib] at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329)
[08:50:40 ERROR]: [BKCommonLib] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620)
[08:50:40 ERROR]: [BKCommonLib] at java.lang.Thread.run(Unknown Source)
[08:50:41 WARN]: java.lang.Exception: Can not load method 'queueChunkLoad' because the class is null!
[08:50:41 WARN]:    at com.bergerkiller.bukkit.common.reflection.SafeMethod.load(SafeMethod.java:59)
[08:50:41 WARN]:    at com.bergerkiller.bukkit.common.reflection.SafeMethod.<init>(SafeMethod.java:54)
[08:50:41 WARN]:    at com.bergerkiller.bukkit.common.reflection.ClassTemplate.getMethod(ClassTemplate.java:253)
[08:50:41 WARN]:    at com.bergerkiller.bukkit.common.reflection.classes.ChunkRegionLoaderRef.<clinit>(ChunkRegionLoaderRef.java:15)
[08:50:41 WARN]:    at java.lang.Class.forName0(Native Method)
[08:50:41 WARN]:    at java.lang.Class.forName(Unknown Source)
[08:50:41 WARN]:    at com.bergerkiller.bukkit.common.Common.loadClasses(Common.java:111)
[08:50:41 WARN]:    at com.bergerkiller.bukkit.common.internal.CommonClasses.loadCommon(CommonClasses.java:59)
[08:50:41 WARN]:    at com.bergerkiller.bukkit.common.internal.CommonClasses.loadRef(CommonClasses.java:45)
[08:50:41 WARN]:    at com.bergerkiller.bukkit.common.internal.CommonClasses.init(CommonClasses.java:21)
[08:50:41 WARN]:    at com.bergerkiller.bukkit.common.internal.CommonPlugin.onLoad(CommonPlugin.java:315)
[08:50:41 WARN]:    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:325)
[08:50:41 WARN]:    at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:458)
[08:50:41 WARN]:    at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:136)
[08:50:41 WARN]:    at net.minecraft.world.World.<init>(World.java:350)
[08:50:41 WARN]:    at net.minecraft.world.WorldServer.<init>(WorldServer.java:153)
[08:50:41 WARN]:    at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:356)
[08:50:41 WARN]:    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329)
[08:50:41 WARN]:    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620)
[08:50:41 WARN]:    at java.lang.Thread.run(Unknown Source)
[08:50:41 INFO]: [Train_Carts] Loading Train_Carts v1.73.1-SNAPSHOT
[08:50:41 INFO]: [BKCommonLib] Enabling BKCommonLib v1.59-SNAPSHOT
[08:50:41 INFO]: [BKCommonLib] BKCommonLib is running on MCPC+ (git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.198) : v1_7_R4 (Minecraft 1.7.10)

---

After loading my old world and getting all my other plugins and mods updated, on trying to spawn a minecart I get the following crash:

[13:03:57 ERROR]: [Train_Carts] Failed to execute REDSTONE_ON for SignActionSpawn:
java.lang.RuntimeException: Could not initialize Entity Class Builder for 'EntityMinecartEmpty':
    at com.bergerkiller.bukkit.common.reflection.ClassBuilder.<init>(ClassBuilder.java:123) ~[?:?]
    at com.bergerkiller.bukkit.common.entity.nms.NMSEntityClassBuilder.<init>(NMSEntityClassBuilder.java:32) ~[?:?]
    at com.bergerkiller.bukkit.common.entity.CommonEntityType.createNMSHookEntity(CommonEntityType.java:125) ~[?:?]
    at com.bergerkiller.bukkit.common.entity.CommonEntity.create(CommonEntity.java:626) ~[?:?]
    at com.bergerkiller.bukkit.tc.controller.MinecartMemberStore.spawn(MinecartMemberStore.java:209) ~[?:?]
    at com.bergerkiller.bukkit.tc.signactions.SignActionSpawn.spawn(SignActionSpawn.java:250) ~[?:?]
    at com.bergerkiller.bukkit.tc.signactions.SignActionSpawn.execute(SignActionSpawn.java:75) ~[?:?]
Caused by: java.lang.RuntimeException: Could not find super method: burn(F)V
    at com.bergerkiller.bukkit.common.reflection.ClassBuilder.<init>(ClassBuilder.java:100) ~[?:?]
    at com.bergerkiller.bukkit.common.entity.nms.NMSEntityClassBuilder.<init>(NMSEntityClassBuilder.java:32) ~[?:?]
    at com.bergerkiller.bukkit.common.entity.CommonEntityType.createNMSHookEntity(CommonEntityType.java:125) ~[?:?]
    at com.bergerkiller.bukkit.common.entity.CommonEntity.create(CommonEntity.java:626) ~[?:?]
    at com.bergerkiller.bukkit.tc.controller.MinecartMemberStore.spawn(MinecartMemberStore.java:209) ~[?:?]
    at com.bergerkiller.bukkit.tc.signactions.SignActionSpawn.spawn(SignActionSpawn.java:250) ~[?:?]
    at com.bergerkiller.bukkit.tc.signactions.SignActionSpawn.execute(SignActionSpawn.java:75) ~[?:?]
    at com.bergerkiller.bukkit.tc.signactions.SignAction.executeAll(SignAction.java:243) [TrainCarts-1.73.1-SNAPSHOT.jar:?]
    at com.bergerkiller.bukkit.tc.signactions.SignAction.executeAll(SignAction.java:222) [TrainCarts-1.73.1-SNAPSHOT.jar:?]
    at com.bergerkiller.bukkit.tc.RedstoneTracker.setRedstonePower(RedstoneTracker.java:160) [TrainCarts-1.73.1-SNAPSHOT.jar:?]
    at com.bergerkiller.bukkit.tc.RedstoneTracker.updateRedstonePower(RedstoneTracker.java:135) [TrainCarts-1.73.1-SNAPSHOT.jar:?]
    at com.bergerkiller.bukkit.tc.RedstoneTracker.onBlockPhysics(RedstoneTracker.java:58) [TrainCarts-1.73.1-SNAPSHOT.jar:?]
    at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_45]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_45]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) [JavaPluginLoader$1.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.198]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [RegisteredListener.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.198]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.198]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.198]
    at net.minecraft.world.World.func_147460_e(World.java:1070) [ahb.class:?]
    at net.minecraft.world.World.func_147459_d(World.java:1020) [ahb.class:?]
    at net.minecraft.block.BlockRedstoneWire.func_150177_e(BlockRedstoneWire.java:83) [ana.class:?]
    at net.minecraft.block.BlockRedstoneWire.func_149695_a(BlockRedstoneWire.java:330) [ana.class:?]
    at net.minecraft.world.World.func_147460_e(World.java:1079) [ahb.class:?]
    at net.minecraft.world.World.func_147459_d(World.java:1017) [ahb.class:?]
    at net.minecraft.block.BlockRedstoneWire.func_150177_e(BlockRedstoneWire.java:83) [ana.class:?]
    at net.minecraft.block.BlockRedstoneWire.func_149695_a(BlockRedstoneWire.java:330) [ana.class:?]
    at net.minecraft.world.World.func_147460_e(World.java:1079) [ahb.class:?]
    at net.minecraft.world.World.func_147459_d(World.java:1017) [ahb.class:?]
    at net.minecraft.block.BlockButton.func_150042_a(BlockButton.java:407) [ajs.class:?]
    at net.minecraft.block.BlockButton.func_149727_a(BlockButton.java:232) [ajs.class:?]
    at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:456) [mx.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:872) [nh.class:?]
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) [jo.class:?]
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) [jo.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.7.0_45]
[13:05:23 ERROR]: Could not pass event EntityAddEvent to Train_Carts v1.73.1-SNAPSHOT
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.198]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.198]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.198]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.198]
    at com.bergerkiller.bukkit.common.utils.CommonUtil.callEvent(CommonUtil.java:125) [BKCommonLib-1.59-SNAPSHOT.jar:?]
    at com.bergerkiller.bukkit.common.internal.CommonWorldListener.func_72703_a(CommonWorldListener.java:70) [BKCommonLib-1.59-SNAPSHOT.jar:?]
    at net.minecraft.world.World.func_72923_a(World.java:1816) [ahb.class:?]
    at net.minecraft.world.WorldServer.func_72923_a(WorldServer.java:1087) [mt.class:?]
    at net.minecraft.world.World.addEntity(World.java:1806) [ahb.class:?]
    at net.minecraft.world.World.func_72838_d(World.java:1693) [ahb.class:?]
    at net.minecraft.item.ItemMinecart.func_77648_a(ItemMinecart.java:98) [adj.class:?]
    at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:170) [add.class:?]
    at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:489) [mx.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:872) [nh.class:?]
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) [jo.class:?]
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) [jo.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.7.0_45]
Caused by: java.lang.RuntimeException: Failed to set controller:
    at com.bergerkiller.bukkit.common.entity.CommonEntity.prepareHook(CommonEntity.java:249) ~[?:?]
    at com.bergerkiller.bukkit.common.entity.CommonEntity.setController(CommonEntity.java:356) ~[?:?]
    at com.bergerkiller.bukkit.tc.controller.MinecartMemberStore.convert(MinecartMemberStore.java:130) ~[?:?]
    at com.bergerkiller.bukkit.tc.TCListener.onEntityAdd(TCListener.java:201) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_45]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_45]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.198]
    ... 22 more
Caused by: java.lang.RuntimeException: Could not initialize Entity Class Builder for 'EntityMinecartEmpty':
    at com.bergerkiller.bukkit.common.reflection.ClassBuilder.<init>(ClassBuilder.java:123) ~[?:?]
    at com.bergerkiller.bukkit.common.entity.nms.NMSEntityClassBuilder.<init>(NMSEntityClassBuilder.java:32) ~[?:?]
    at com.bergerkiller.bukkit.common.entity.CommonEntityType.createNMSHookEntity(CommonEntityType.java:125) ~[?:?]
    at com.bergerkiller.bukkit.common.entity.CommonEntity.prepareHook(CommonEntity.java:245) ~[?:?]
    at com.bergerkiller.bukkit.common.entity.CommonEntity.setController(CommonEntity.java:356) ~[?:?]
    at com.bergerkiller.bukkit.tc.controller.MinecartMemberStore.convert(MinecartMemberStore.java:130) ~[?:?]
    at com.bergerkiller.bukkit.tc.TCListener.onEntityAdd(TCListener.java:201) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_45]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_45]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.198]
    ... 22 more
Caused by: java.lang.RuntimeException: Could not find super method: burn(F)V
    at com.bergerkiller.bukkit.common.reflection.ClassBuilder.<init>(ClassBuilder.java:100) ~[?:?]
    at com.bergerkiller.bukkit.common.entity.nms.NMSEntityClassBuilder.<init>(NMSEntityClassBuilder.java:32) ~[?:?]
    at com.bergerkiller.bukkit.common.entity.CommonEntityType.createNMSHookEntity(CommonEntityType.java:125) ~[?:?]
    at com.bergerkiller.bukkit.common.entity.CommonEntity.prepareHook(CommonEntity.java:245) ~[?:?]
    at com.bergerkiller.bukkit.common.entity.CommonEntity.setController(CommonEntity.java:356) ~[?:?]
    at com.bergerkiller.bukkit.tc.controller.MinecartMemberStore.convert(MinecartMemberStore.java:130) ~[?:?]
    at com.bergerkiller.bukkit.tc.TCListener.onEntityAdd(TCListener.java:201) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_45]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_45]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.198]
    ... 22 more
[13:05:30 ERROR]: Could not pass event PlayerInteractEvent to Movecraft v3.1.46
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.198]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.198]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.198]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.198]
    at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:223) [CraftEventFactory.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.198]
    at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:422) [mx.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:872) [nh.class:?]
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) [jo.class:?]
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) [jo.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.7.0_45]
Caused by: java.lang.NullPointerException
    at net.countercraft.movecraft.listener.InteractListener.getCraftTypeFromString(InteractListener.java:229) ~[?:?]
    at net.countercraft.movecraft.listener.InteractListener.onSignRightClick(InteractListener.java:106) ~[?:?]
    at net.countercraft.movecraft.listener.InteractListener.onPlayerInteract(InteractListener.java:50) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_45]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_45]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.198]
    ... 15 more
[13:05:46 ERROR]: Could not pass event PlayerInteractEvent to Movecraft v3.1.46
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.198]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.198]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.198]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.198]
    at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:223) [CraftEventFactory.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.198]
    at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:422) [mx.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:872) [nh.class:?]
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) [jo.class:?]
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) [jo.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.7.0_45]
Caused by: java.lang.NullPointerException
    at net.countercraft.movecraft.listener.InteractListener.getCraftTypeFromString(InteractListener.java:229) ~[?:?]
    at net.countercraft.movecraft.listener.InteractListener.onSignRightClick(InteractListener.java:106) ~[?:?]
    at net.countercraft.movecraft.listener.InteractListener.onPlayerInteract(InteractListener.java:50) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_45]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_45]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.198]
    ... 15 more

**Comment by lenis0012** [comment]
@PsychoLynx Need to find time to do updates :(

**Comment by vpontin** [comment]
@lenis0012 due to shutdown of original Caudron, a guy called prototik took over the project and rename it KCauldron. He's active developing that now.

If you and dev team still wants to offer support for bkcommonlib (and traincarts xD) to Cauldron, here is the repository home: https://gitlab.prok.pw/Prototik/KCauldron

And you can find extra information (and regular builds) in Yive's Mirror (http://tcpr.ca/).

Good luck!

**Comment by giquon** [comment]
I'm having the same problem, have you found a solution yet? Kcauldron doesn't work for me. If it works for you could you please help me?

**Comment by NDruce** [comment]
I started porting it, for now everything is going well! But it about 74 classes remaining porting... I hate this, even it 100% will work :)
