### ISSUE TITLE
Error in console on startup

### ISSUE THREAD

**Issue by HollishKid** [bergerkiller/BKCommonLib#31]
Hello,

Not sure whether this is still active, but I get the following error when using latest build:

If you have any suggestions ... ^^

[01:52:14] [Server thread/INFO]: [BKCommonLib] Loading BKCommonLib v1.67-SNAPSHOT
[01:52:14] [Server thread/ERROR]: [BKCommonLib] [Reflection] Field 'timestamp' does not exist in class file net.minecraft.server.v1_8_R3.PacketPlayInArmAnimation (Update BKCommonLib?)
[01:52:14] [Server thread/ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.internal.CommonPlugin.handleReflectionMissing(CommonPlugin.java:92)
[01:52:14] [Server thread/ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.reflection.SafeField.load(SafeField.java:80)
[01:52:14] [Server thread/ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.reflection.SafeField.<init>(SafeField.java:59)
[01:52:14] [Server thread/ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.reflection.ClassTemplate.getField(ClassTemplate.java:253)
[01:52:14] [Server thread/ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.protocol.PacketTypeClasses$NMSPacketPlayInArmAnimation.<init>(PacketTypeClasses.java:715)
[01:52:14] [Server thread/ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.protocol.PacketType.<clinit>(PacketType.java:109)
[01:52:14] [Server thread/ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.reflection.classes.EntityTrackerRef.<clinit>(EntityTrackerRef.java:25)
[01:52:14] [Server thread/ERROR]: [BKCommonLib] at java.lang.Class.forName0(Native Method)
[01:52:14] [Server thread/ERROR]: [BKCommonLib] at java.lang.Class.forName(Class.java:186)
[01:52:14] [Server thread/ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.Common.loadClasses(Common.java:111)
[01:52:14] [Server thread/ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.internal.CommonClasses.loadCommon(CommonClasses.java:61)
[01:52:14] [Server thread/ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.internal.CommonClasses.loadRef(CommonClasses.java:47)
[01:52:14] [Server thread/ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.internal.CommonClasses.init(CommonClasses.java:21)
[01:52:14] [Server thread/ERROR]: [BKCommonLib] at com.bergerkiller.bukkit.common.internal.CommonPlugin.onLoad(CommonPlugin.java:308)
[01:52:14] [Server thread/ERROR]: [BKCommonLib] at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:294)
[01:52:14] [Server thread/ERROR]: [BKCommonLib] at org.bukkit.craftbukkit.v1_8_R3.CraftServer.<init>(CraftServer.java:251)
[01:52:14] [Server thread/ERROR]: [BKCommonLib] at net.minecraft.server.v1_8_R3.PlayerList.<init>(PlayerList.java:69)
[01:52:14] [Server thread/ERROR]: [BKCommonLib] at net.minecraft.server.v1_8_R3.DedicatedPlayerList.<init>(SourceFile:14)
[01:52:14] [Server thread/ERROR]: [BKCommonLib] at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:179)
[01:52:14] [Server thread/ERROR]: [BKCommonLib] at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:504)
[01:52:14] [Server thread/ERROR]: [BKCommonLib] at java.lang.Thread.run(Thread.java:722)
[01:52:14] [Server thread/INFO]: [Train_Carts] Loading Train_Carts v1.75-SNAPSHOT
[01:52:14] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v3.6.5
[01:52:14] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[01:52:16] [Server thread/INFO]: [BKCommonLib] Enabling BKCommonLib v1.67-SNAPSHOT
[01:52:16] [Server thread/INFO]: [BKCommonLib] BKCommonLib is running on CraftBukkit (git-Bukkit-18fbb24) : v1_8_R3 (Minecraft 1.8.8)
[01:52:16] [Server thread/INFO]: [BKCommonLib] [Network] Now using the ProtocolLib library to provide Packet Listener and Monitor support
[01:52:16] [Server thread/ERROR]: [BKCommonLib] Common.VERSION needs to be updated to contain '167'!
[01:52:16] [Server thread/INFO]: [BKCommonLib] This library is written with stability in mind.
[01:52:16] [Server thread/INFO]: BKCommonLib version 1.67-SNAPSHOT enabled! (0.079s)

**Comment by vpontin** [comment]
Using (K)Cauldron?
