### ISSUE TITLE
My problem

### ISSUE THREAD

**Issue by Andxls** [bergerkiller/BKCommonLib#35]
I have this problem, help me please

[22:37:22] [Server thread/ERROR]: Could not load 'plugins/BKCommonLib-1.19.3-v3-1512.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.VerifyError: Inconsistent stackmap frames at branch target 192
Exception Details:
  Location:
    com/bergerkiller/bukkit/common/internal/CommonPlugin.<init>()V @179: ifne
  Reason:
    Current frame's stack size doesn't match stackmap.
  Current Frame:
    bci: @179
    flags: { }
    locals: { 'com/bergerkiller/bukkit/common/internal/CommonPlugin' }
    stack: { 'com/bergerkiller/bukkit/common/internal/regionchangetracker/RegionchangetrackerLoader', integer }
  Stackmap Frame:
    bci: @192
    flags: { }
    locals: { 'com/bergerkiller/bukkit/common/internal/CommonPlugin' }
    stack: { }
  Bytecode:
    0000000: bb00 7459 b700 762a b700 772a 2ab8 007d
    0000010: b500 7f2a bb00 8159 b700 82b5 0084 2abb
    0000020: 0081 59b7 0082 b500 862a bb00 8159 04b7
    0000030: 0089 b500 8b2a bb00 8159 b700 82b5 008d
    0000040: 2abb 008f 59b7 0090 b500 922a bb00 9459
    0000050: b700 95b5 0097 2a03 b500 992a 01b5 009b
    0000060: 2a01 b500 9d2a bb00 9f59 2ab7 00a2 b500
    0000070: a42a 01b5 00a6 2a01 b500 a82a 01b5 00aa
    0000080: 2aba 00bd 0000 b500 bf2a 04b5 00c1 2a04
    0000090: b500 c32a 04b5 00c5 2a04 b500 c72a 03b5
    00000a0: 00c9 2a03 b500 cb2a 03b5 00cd 2ab6 00d1
    00000b0: b800 d79a 000d bb00 d959 12db b700 debf
    00000c0: 2abb 00e0 5906 0614 00e1 b200 e8bb 00ea
    00000d0: 5911 0400 b700 ebba 00f5 0000 b700 f8b5
    00000e0: 00fa 2ab4 00fa 04b6 00fe 2ab6 00d1 b301
    00000f0: 042a b301 06b1                         
  Stackmap Table:
    full_frame(@192,{Object[#2]},{})

	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:393) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:269) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.VerifyError: Inconsistent stackmap frames at branch target 192
Exception Details:
  Location:
    com/bergerkiller/bukkit/common/internal/CommonPlugin.<init>()V @179: ifne
  Reason:
    Current frame's stack size doesn't match stackmap.
  Current Frame:
    bci: @179
    flags: { }
    locals: { 'com/bergerkiller/bukkit/common/internal/CommonPlugin' }
    stack: { 'com/bergerkiller/bukkit/common/internal/regionchangetracker/RegionchangetrackerLoader', integer }
  Stackmap Frame:
    bci: @192
    flags: { }
    locals: { 'com/bergerkiller/bukkit/common/internal/CommonPlugin' }
    stack: { }
  Bytecode:
    0000000: bb00 7459 b700 762a b700 772a 2ab8 007d
    0000010: b500 7f2a bb00 8159 b700 82b5 0084 2abb
    0000020: 0081 59b7 0082 b500 862a bb00 8159 04b7
    0000030: 0089 b500 8b2a bb00 8159 b700 82b5 008d
    0000040: 2abb 008f 59b7 0090 b500 922a bb00 9459
    0000050: b700 95b5 0097 2a03 b500 992a 01b5 009b
    0000060: 2a01 b500 9d2a bb00 9f59 2ab7 00a2 b500
    0000070: a42a 01b5 00a6 2a01 b500 a82a 01b5 00aa
    0000080: 2aba 00bd 0000 b500 bf2a 04b5 00c1 2a04
    0000090: b500 c32a 04b5 00c5 2a04 b500 c72a 03b5
    00000a0: 00c9 2a03 b500 cb2a 03b5 00cd 2ab6 00d1
    00000b0: b800 d79a 000d bb00 d959 12db b700 debf
    00000c0: 2abb 00e0 5906 0614 00e1 b200 e8bb 00ea
    00000d0: 5911 0400 b700 ebba 00f5 0000 b700 f8b5
    00000e0: 00fa 2ab4 00fa 04b6 00fe 2ab6 00d1 b301
    00000f0: 042a b301 06b1                         
  Stackmap Table:
    full_frame(@192,{Object[#2]},{})

	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:466) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[patched_1.16.5.jar:git-Paper-794]
	... 7 more

**Comment by lenis0012** [comment]
This repository is no longer used, please visit https://github.com/bergerhealer/BKCommonLib and make sure you are using the latest version on spigotmc.org
